###
GET http://localhost/items

###
GET http://localhost/posts

###
GET http://localhost/posts/31

###
POST http://localhost/posts/
Content-Type: application/json

{
  "title": "Social media and teenage health-31",
  "body": "What are the health risks of social media for teenagers?"
}

###
POST http://localhost/posts/
Content-Type: application/json


###
PUT http://localhost/posts/31
Content-Type: application/json

{
  "title": "How fans talk about their passions-31-updated",
  "body": "What language do fans use?"
}

###
DELETE http://localhost/posts/32