###
GET http://localhost/items

###
GET http://localhost/api/posts

###
GET http://localhost/api/posts/43

###
POST http://localhost/api/posts
Content-Type: application/json

{
  "title": "Social media and teenage health-100",
  "body": "What are the health risks of social media for teenagers?"
}

###
POST http://localhost/api/posts
Content-Type: application/json


###
PUT http://localhost/api/posts/1
Content-Type: application/json

{
  "title": "How fans talk about their passions-60-updated!!!!",
  "body": "What language do fans use?"
}

###
DELETE http://localhost/api/posts/61
